### PR TITLE
Updates for Ruby 2.4 openssl 1.1 compatibility

### PR DESCRIPTION
**Pull request by lampad**
Hopefully a fix for #122 

Breaking changes:
* Remove support for DSS1 - Ruby's openssl bindings appear to have removed support for it in 2.4.x too.

Specs on all currently supported versions of Ruby (2.2.8, 2.3.5, 2.4.2)

### CODE REVIEW

**Comment by reaperhulk** [comment]
The test that's failing may not be a useful test here since it's dependent on underlying OpenSSL version...

**Comment by reaperhulk** [comment]
Ah you just reverted, that's okay for Travis.

**Comment by lampad** [comment]
Yeah that was my hunch too. Interestingly, it failed locally on me, i figured i'd trust Travis though.

**Comment by lampad** [comment]
Basing the different expectations off of the ruby version probably wasn't the best idea anyway.

**Comment by lampad** [comment]
I can't figure out where I decreased coverage based on coveralls' report. It looks like it's for Ruby Head, but if you can point it out for me i'd be happy to regain that .0002%

**Comment by reaperhulk** [comment]
.0002% seems...unlikely to be accurate (and the actual coveralls output is also suspicious). I think we're fine here. Thanks for the contribution!

**Comment by pschambacher** [comment]
❤️ 
Can we get a new version including this commit?

**Comment by reaperhulk** [comment]
Sure, running a release now.

**Comment by reaperhulk** [comment]
Released as 1.0.1

**Pull request merged**
