### PR TITLE
Add option to encrypt generated keys to r509 binary

### PR DESCRIPTION
**Pull request by smartinm**
Simple support to encrypt the generated private key file using aes256.

### CODE REVIEW

**Comment by reaperhulk** [comment]
Could you use `IO.noecho` to prevent the password from being visible in the shell? Other than that this looks good to me.

**Comment by smartinm** [comment]
OK! I done it.

**Comment by reaperhulk** [comment]
One more small change if you don't mind: could you add a password confirmation to the interactive prompt? That way users will know if they've mistyped the password they want to use.

**Comment by smartinm** [comment]
Hi again!

I added password confirmation to the interactive prompt, if passwords do not match, abort execution. Or, if you prefer, I can do a loop to until there's a match?

**Comment by reaperhulk** [comment]
Nope this looks good, thanks for the contribution!

**Pull request merged**
